### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ryannix123** [theeternalsw0rd/homebrew-telnet#1]
Hi Micah,

Thanks for building this. I'm trying to install on Sierra through brew but I'm getting the following back:
brew install telnet
Error: No available formula with the name "telnet" 
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

I also did:

brew list | grep telnet*

which didn't return anything.
How do I install your telnet package?

Thanks!

- Ryan

**Comment by theeternalsw0rd** [comment]
I've added installation instructions to the readme.

```
brew tap theeternalsw0rd/telnet
brew install telnet
```
