### ISSUE TITLE
install telnet fail 

### ISSUE THREAD

**Issue by dufengtao** [theeternalsw0rd/homebrew-telnet#3]
➜  ~ brew install telnet
Warning: You are using OS X 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
==> Installing telnet from theeternalsw0rd/telnet
==> Downloading https://github.com/theeternalsw0rd/telnet-macos/archive/1.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/telnet-1.2.tar.gz
==> ./configure --prefix=/usr/local/Cellar/telnet/1.2_1
Last 15 lines from /Users/dft/Library/Logs/Homebrew/telnet/01.configure:
--prefix=/usr/local/Cellar/telnet/1.2_1

checking build system type... i686-apple-darwin17.3.0
checking host system type... i686-apple-darwin17.3.0
checking target system type... i686-apple-darwin17.3.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for gcc... clang
checking for C compiler default output file name... configure: error: C compiler cannot create executables
See `config.log' for more details.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/theeternalsw0rd/homebrew-telnet/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:359:in `open_http': 422 Unprocessable Entity (GitHub::Error)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:31:in `open'
	from /usr/local/Library/Homebrew/utils.rb:523:in `open'
	from /usr/local/Library/Homebrew/utils.rb:553:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:585:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:222:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:218:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:263:in `dump'
	from /usr/local/Library/brew.rb:134:in `rescue in <main>'
	from /usr/local/Library/brew.rb:32:in `<main>'

**Comment by theeternalsw0rd** [comment]
Closing this issue due to problem being with user's compiler or build environment.
